name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * 2,6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
        cd ..
        
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        git fetch origin google-scholar-stats || true
        git checkout -B google-scholar-stats origin/google-scholar-stats || git checkout -B google-scholar-stats

       
        cp google_scholar_crawler/results/gs_data.json .
        cp google_scholar_crawler/results/gs_data_shieldsio.json .
        git add gs_data.json gs_data_shieldsio.json
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" google-scholar-stats --force
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
